on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  managed_service_identity_check:
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.checksecret.outputs.validated }}
    steps:
      - name: Secrets are set
        id: checksecret
        if: ${{ env.ARM_CLIENT_ID != null && env.ARM_SUBSCRIPTION_ID != null && env.ARM_TENANT_ID != null }}
        run: |
          set -x
          echo "validated=true" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

      - name: Az CLI login with OIDC
        if: ${{ steps.checksecret.output.validated == true }}
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        if: ${{ steps.checksecret.output.validated == true }}
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
