on:
  workflow_call:

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

permissions:
  id-token: write
  contents: read

jobs:
  managed_service_identity_check:
    runs-on: ubuntu-latest
    outputs:
      is_ARM_CLIENT_ID_set: ${{ steps.checksecret.outputs.is_ARM_CLIENT_ID_set }}
      is_ARM_SUBSCRIPTION_ID_set: ${{ steps.checksecret.outputs.is_ARM_SUBSCRIPTION_ID_set }}
      is_ARM_TENANT_ID_set: ${{ steps.checksecret.outputs.is_ARM_TENANT_ID_set }}
    steps:

      # Use secrets and test login before returning any outputs
      - name: Az CLI login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list

      - name: Secrets are set
        id: checksecret
        run: |
          set -x
          echo "is_ARM_CLIENT_ID_set=${{ env.ARM_CLIENT_ID != '' }}" >> $GITHUB_OUTPUT
          echo "is_ARM_SUBSCRIPTION_ID_set=${{ env.ARM_SUBSCRIPTION_ID != '' }}" >> $GITHUB_OUTPUT
          echo "is_ARM_TENANT_ID_set=${{ env.ARM_TENANT_ID != '' }}" >> $GITHUB_OUTPUT
